services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped

    ports:
      # AMQP，应用连接 RabbitMQ 用
      - "5672:5672"

      # RabbitMQ Management UI
      - "15672:15672"

      # RabbitMQ Prometheus metrics
      - "15692:15692"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ".netcore"
      RABBITMQ_DEFAULT_VHOST: /

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - observability

volumes:
  rabbitmq_data:

networks:
  observability:
    external: true